### ISSUE TITLE
Showing switcher blocks changing to a new workspace

### ISSUE THREAD

**Issue by alejnp** [mrEDitor/gnome-shell-extension-scroll-panel#13]
Steps to reproduce
===

- Enable "show switcher" toggle.
- Scroll on the topbar to change workspaces.

Expected Result
===

- Switcher comes into view.
- Scroll again to move workspaces (based on pressure settings)

Current Result
===

- Switcher comes into view.
- Scroll again to move workspaces (blocked until switcher goes out of view)

**Comment by mrEDitor** [comment]
The problem is actually to default gnome workspace switcher popup [covers all the display](https://github.com/GNOME/gnome-shell/blob/mainline/js/ui/workspaceSwitcherPopup.js#L122) when shown and blocks user interaction with other actors, including top panel.
I've added little dirty hack that moves workspace switcher a little bit to the down when it's spawned by the extension, to unblock further scrolling, but it can break overall visual design or something like that.
Any better ideas are appreciated.

@Alxe, I'll also be grateful for feedback about this before pushing it to the extensions store. If you don't mind, follow [the build instructions](https://github.com/mrEDitor/gnome-shell-extension-scroll-panel#build) and drop a line here, is it any better with the workaround.

**Comment by alejnp** [comment]
Hello, sorry for the delay.

The issue with testing this extension is that my personal laptop broke a hinge and is currently unusable.

There's [a different extension](https://extensions.gnome.org/extension/701/top-panel-workspace-scroll/) that serves the same use case. Maybe you can see how they approached their solution?

**Comment by mrEDitor** [comment]
Thanks for the link! Shame on me, I didn't notice popup method to make it non-blocking, now I've figured out the right way to fix this. I've updated the extension, you can fetch it from [repository releases](https://github.com/mrEDitor/gnome-shell-extension-scroll-panel/releases/) now.
I suppose, the issue is resolved now.
